### PR TITLE
more powerful notebook VM

### PR DESCRIPTION
**Pull request by rabernat**
I think it would be good to have more RAM and CPU in the main notebook pod. Since that's where the scheduler runs, RAM can become a bottleneck for large dask graphs. Also, the notebook pod has to do more work than the worker pods because it does all the visualization etc.

Would this change accomplish that?

### CODE REVIEW

**Comment by mrocklin** [comment]
It looks like you might also want to set request?  http://callmeradical.com/post/k8s-resource-limits-requests-qos/  I'm not sure.

Two other points

1.  I think that our VM's cpu:memory ratio is something like 1:3G  .  I recommend sticking to this.  Leaving CPU on the table at the pod-level doesn't reduce our bill at all.
2.  Currently none of our node pools have VMs large enough to run 16GB pods.  I suggest that we increase the size of the nodes in the pre-emptible pool.  You should be able to do this in the [cloud console](https://console.cloud.google.com/kubernetes/list?project=pangeo-181919).

**Comment by mrocklin** [comment]
@jacobtomlinson any thoughts on what's going on with the travis test failure on this PR?

**Comment by rabernat** [comment]
the test failure might have to do with the fact that I just make a quick PR by editing within github (rather than forking / branching / pushing) and therefore created another branch `rabernat-patch-1` within this repo.

**Comment by jacobtomlinson** [comment]
The error comes from chartpress. I wouldn't worry for now. I'm actively looking at updating the Travis stuff on this repo.

While I agree that this makes sense I'm wondering if we shouldn't be updating the defaults here and instead updating the GCE deployment config [here](https://github.com/pangeo-data/pangeo/blob/master/gce/jupyter-config.yaml).

I guess it depends if you think this change should be made for everyone, or just for pangeo.pydata.org. Happy to defer to you on this!

**Comment by rabernat** [comment]
I agree it makes sense to update the pangeo.pydata.org specific config, rather than the master template. The problem is that I don’t understand the relationship between these pieces very well.

**Comment by jacobtomlinson** [comment]
That's fair.

This repo is the master template. Perhaps I should update the README to make that clearer.

**Comment by rabernat** [comment]
What is the relationship between `values.yaml` in this repo and `pangeo/gce/jupyter-config.yaml` in the other repo? Does that one somehow "extend" this one?

**Comment by mrocklin** [comment]
nYes, the config files stack.

**Pull request closed without merging**
