### PR TITLE
[WIP] remove notebook docker image

### PR DESCRIPTION
**Pull request by jhamman**
This removes the docker image from this repo. This shouldNOT be merged until we have something like a pangeo-stacks repo in place.

cc @guillaumeeb

### CODE REVIEW

**Comment by guillaumeeb** [comment]
Linking to https://github.com/pangeo-data/pangeo/issues/525.

I'm perfectly fine with this, obviously. But let's build this other repo first 😃 !

**Comment by jhamman** [comment]
@guillaumeeb - I got a start here: https://github.com/pangeo-data/pangeo-stacks

We have a few things to sort out with repo2docker before this approach works.

**Comment by jhamman** [comment]
@guillaumeeb - care to take a look here again?

**Comment by guillaumeeb** [comment]
Is this currently plugged with one image built from https://github.com/pangeo-data/pangeo-stacks? (I don't think so, but just asking).

How and when do you plan to merge this?

We should probably add some comment somewhere, in the readme or directly in the chart, to inform that we are using images built from pangeo-stacks repo.

Other than that, I don't know what impacts the changes to the chartpress.yaml have...

**Comment by jhamman** [comment]
> Is this currently plugged with one image built from https://github.com/pangeo-data/pangeo-stacks?

Yes, the pangeo/pangeo-notebook image is now on [dockerhub](https://hub.docker.com/r/pangeo/pangeo-notebook) and is built from [this](https://github.com/pangeo-data/pangeo-stacks) directory.

> How and when do you plan to merge this?

Not sure I follow. Once @jacobtomlinson is also happy, I'll press the merge button :)

> We should probably add some comment somewhere, in the readme or directly in the chart, to inform that we are using images built from pangeo-stacks repo.

I'll add some notes to the readme.

**Review by guillaumeeb — APPROVED** [review]
Sorry, I was convinced you did not already built an image with docker-stack repo. 

This looks perfect!

**Review by jacobtomlinson — APPROVED** [review]
Looks reasonable to me!

**Pull request merged**
