### PR TITLE
Release: update version number

### PR DESCRIPTION
**Pull request by guillaumeeb**
First step for #31.

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
We should probably make this a template that is populated dynamically at build time. Like using versioneer in Python.

**Comment by jhamman** [comment]
> We should probably make this a template that is populated dynamically at build time. Like using versioneer in Python.

Is that something we should ask chartpress to do?

**Comment by guillaumeeb** [comment]
> > We should probably make this a template that is populated dynamically at build time. Like using versioneer in Python.

> Is that something we should ask chartpress to do?

Yeah, I think maybe we could by reading the docs. And probably we could have a special process on git tags to build real release... Sorry again to not being able to give more time to this currently, I'm not sure I will be able to dig this further until the beginning of march...

**Comment by guillaumeeb** [comment]
Closing, as overriden by #85.

**Pull request closed without merging**
