### PR TITLE
pin chartpress version at 0.3.2

### PR DESCRIPTION
**Pull request by jhamman**
cc @consideRatio

### CODE REVIEW

**Review by consideRatio — APPROVED** [review]

**Comment by jhamman** [comment]
It seems like our minikube ci build is failing for unrelated reasons.

**Review by jacobtomlinson — APPROVED** [review]

**Comment by consideRatio** [comment]
The situation has now been resolved I think. In chartpress 0.4.3 there is some new versioning behavior, but it isn't in a broken state.

The versions created by chartpress will be instead of `0.9.0-asdf123` become 0.9.0-009.asdf123 for a chart changed 9 commits after the tag 0.9.0 for example.

**Comment by jhamman** [comment]
@consideRatio - IIRC, you recently worked on z2jh's CI system. As I understand, z2jh has moved to [kind](https://kind.sigs.k8s.io/). Our minikube CI has stopped working. I'm also unable to get it working locally so I'm trying to decide whether to invest in fixing our minikube setup or moving to kind to stay in sync with z2jh. Thoughts on this idea are welcome.

**Comment by consideRatio** [comment]
Id suggest trying out the z2jh "dev" script locally, i spent lots on time on that, and considering what would need to be adjusted for that to be useful for your chart.

**Pull request merged**
