### PR TITLE
Dask gateway 2

### PR DESCRIPTION
**Pull request by TomAugspurger**
Basically the same as #102. Just trying a fresh CI run.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
This worked for me locally, hopefully it does it.

**Comment by TomAugspurger** [comment]
Yay, that passed. No idea about the TravisCI failure.


```
0.60s$ chartpress --commit-range ${TRAVIS_COMMIT_RANGE} --tag `date +%y.%m.%d`

Warning: use of --commit-range is deprecated.

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.6.7/bin/chartpress", line 10, in <module>

    sys.exit(main())

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/chartpress.py", line 693, in main

    for image_name, image_config in chart['images'].items():

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/ruamel/yaml/comments.py", line 753, in __getitem__

    return ordereddict.__getitem__(self, key)

KeyError: 'images'

The command "chartpress --commit-range ${TRAVIS_COMMIT_RANGE} --tag `date +%y.%m.%d`" exited with 1.
```

Two things

1. `--commit-range` is deprecated. Maybe not needed anymore though?
2. In https://github.com/jupyterhub/chartpress the docs say that the `images` key in `chartpress.yaml` is option, but we're getting a KeyError there. Trying to figure out what's appropriate.

**Comment by TomAugspurger** [comment]
@yuvipanda can you check out 24dba073455b770af0c895afb787ee1014ee1464, which (maybe) gets around the KeyError raised by chartpress, due to this helm chart not having any associated images? This is my first time using chartpress, so I may be doing something wrong.

And if this is a bug on the chartpress side of things, I'll file an issue.

**Comment by jhamman** [comment]
I plan to merge this on Monday afternoon unless I hear specific objections. Thanks @TomAugspurger for getting CI working.

**Pull request merged**
