### PR TITLE
bump gateway to 0.7

### PR DESCRIPTION
**Pull request by jhamman**
cc @TomAugspurger & @scottyhq

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Will have some config updates to push here.

**Comment by jhamman** [comment]
@TomAugspurger - feel free to push changes to this branch.

**Comment by consideRatio** [comment]
I opened two issues in dask-gateway 0.7.0 that may be relevant for you about this:
- https://github.com/dask/dask-gateway/issues/240
- https://github.com/dask/dask-gateway/issues/239

**Comment by TomAugspurger** [comment]
Superseded by #128

**Pull request closed without merging**
