### PR TITLE
remove resource specs

### PR DESCRIPTION
**Pull request by rabernat**
After some discussion with @tjcrone, I am starting to think that the resource specs should be specified in the deployment-specific config (e.g. [jupyter-config.yaml](https://github.com/pangeo-data/pangeo/blob/master/gce/jupyter-config.yaml) for pangeo.pydata.org), rather than here in the generic helm chart. We override them there already, so their presence here is confusing.

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
I disagree that we should remove these as failing to set these specs can cause knock on issues such as autoscaling not working properly.

I agree that it is unclear and that we override regularly but perhaps the values should be updated to be suit more use cases and the docs should be updated.

**Comment by mrocklin** [comment]
My understanding was that in order to serve minikube users the standard was
to not include resources in helm charts

**Comment by rabernat** [comment]
> I disagree that we should remove these as failing to set these specs can cause knock on issues such as autoscaling not working properly.

But is anyone deploying this chart directly? All the pangeo cloud deployments I know of overwrite these values. We could simply state in the docs that they need to be specified in the deployment-specific config. 

But unfortunately, there are no docs.

**Comment by jacobtomlinson** [comment]
There is nothing stopping people deploying this directly, I would expect people to override these values but values should exist to override. I have seen other examples where this section is there but commented out which helps provide an example usage.

By docs in this instance I meant README.

**Comment by mrocklin** [comment]
> I would expect people to override these values but values should exist to override

I think that when I was working on the stable/dask chart maintainers recommended that I comment out resources so that things could be easily tested on minikube, the idea being that any serious use was likely to override them anyway.  Thoughts on this?  I would find this useful personally.  I would probably test things more often locally before deploying to the live cluster.  This slightly puts off the need of a staging environment for a bit.

**Comment by mrocklin** [comment]
> I have seen other examples where this section is there but commented out which helps provide an example usage.

I'm in favor of this

**Comment by jacobtomlinson** [comment]
Great!

**Comment by rabernat** [comment]
Let's wait until #29 is merged before messing with the charts any more.

**Comment by mrocklin** [comment]
Waiting on #29 seems to have been less-than-wise.  I'm in favor of merging this.

**Comment by jhamman** [comment]
#29 has been merged. Do we want to resolve these conflicts and merge or has this fallen out of favor?

**Comment by jacobtomlinson** [comment]
After researching this more I retract my previous concerns. I would be happy for this to be resolved and merged.

**Comment by jhamman** [comment]
I'm clearing out some old issues. I plan to merge this if the CI tests pass.

**Pull request merged**
