### PR TITLE
bump version of pangeo notebook

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Comment by mrocklin** [comment]
For some reason this doesn't show up at https://pangeo-data.github.io/helm-chart/ 

I had thought that there was an automated system to publish charts in place.  Is there a reason why this would not have triggered?  cc @jacobtomlinson

**Comment by rabernat** [comment]
Looks like Travis failed:
https://travis-ci.org/pangeo-data/helm-chart/builds/375921137

**Comment by rabernat** [comment]
(I just triggered a manual re-build.)

**Comment by rabernat** [comment]
Looks like a pip problem:
```
$ pip install git+https://github.com/jupyterhub/chartpress.git
Collecting git+https://github.com/jupyterhub/chartpress.git
  Cloning https://github.com/jupyterhub/chartpress.git to /tmp/pip-h6101jv_-build
Collecting ruamel.yaml>=0.15 (from chartpress==0.2.0.dev0)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f1a7f131da0>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/98/cc/ba3b6ccd0a4f6c51d128742fc5f0f43ae570d67174342578591c50f30013/ruamel.yaml-0.15.37-cp36-cp36m-manylinux1_x86_64.whl
```

**Comment by rabernat** [comment]
Looks like the build finally succeeded. I will try to deploy now.

**Comment by mrocklin** [comment]
When you finish let me know and I'll update with
https://github.com/pangeo-data/pangeo/pull/240 .  Hopefully at that point
we'll both by in sync.

**Pull request merged**
